// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as IhpBackend from "ihp-backend";
import * as React$1 from "ihp-backend/react";

function Logout(Props) {
  var user = React$1.useCurrentUser();
  var onClick = function (param) {
    IhpBackend.logout();
    
  };
  if (user == null) {
    return React.createElement("span", undefined);
  } else {
    return React.createElement("a", {
                className: "text-muted",
                id: "logout",
                href: "#",
                onClick: onClick
              }, "Logout " + user.email);
  }
}

var make = Logout;

export {
  make ,
  
}
/* react Not a pure module */
