// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as IhpBackend from "ihp-backend";

IhpBackend.initIHPBackend({
      host: process.env.BACKEND_URL
    });

var root = document.querySelector("#app");

if (!(root == null)) {
  ReactDom.render(React.createElement(App.make, {}), root);
}

export {
  
}
/*  Not a pure module */
