// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as IhpBackend from "ihp-backend";

function prompt(message, defValue) {
  return (window.prompt(message, defValue));
}

function MessageActions(Props) {
  var message = Props.message;
  var onDeleteClick = function ($$event) {
    $$event.preventDefault();
    IhpBackend.deleteRecord("messages", message.id);
    
  };
  var onEditClick = function ($$event) {
    $$event.preventDefault();
    IhpBackend.updateRecord("messages", message.id, {
          id: message.id,
          body: prompt("Update message", message.body),
          userId: message.userId,
          createdAt: message.createdAt,
          updatedAt: message.updatedAt,
          channelId: message.channelId
        });
    
  };
  return React.createElement("div", {
              className: "actions"
            }, React.createElement("a", {
                  className: "js-delete text-muted",
                  href: "#",
                  onClick: onDeleteClick
                }, "Delete message"), React.createElement("a", {
                  className: "text-muted",
                  href: "#",
                  onClick: onEditClick
                }, "Edit Message"));
}

var make = MessageActions;

export {
  prompt ,
  make ,
  
}
/* react Not a pure module */
