// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Message from "./Message.bs.js";
import * as Belt_Array from "../node_modules/rescript/lib/es6/belt_Array.js";
import * as IhpBackend from "ihp-backend";
import * as NewMessageForm from "./NewMessageForm.bs.js";
import * as React$1 from "ihp-backend/react";
import * as NewMessageFormIfLoggedOut from "./NewMessageFormIfLoggedOut.bs.js";

function MessagesContainer(Props) {
  var channelId = Props.channelId;
  var messages = React$1.useQuery(IhpBackend.query("messages").filterWhere("channelId", channelId).orderBy("createdAt"));
  var isLoggedIn = React$1.useIsLoggedIn();
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "messages"
                }, (messages == null) ? React.createElement("div", undefined) : Belt_Array.map(messages, (function (message) {
                          return React.createElement(Message.make, {
                                      message: message,
                                      key: message.id
                                    });
                        }))), (isLoggedIn == null) ? React.createElement("div", undefined) : (
                isLoggedIn ? React.createElement(NewMessageForm.make, {
                        channelId: channelId
                      }) : React.createElement(NewMessageFormIfLoggedOut.make, {})
              ));
}

var make = MessagesContainer;

export {
  make ,
  
}
/* react Not a pure module */
