// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as React from "react";
import * as IhpBackend from "ihp-backend";
import * as React$1 from "ihp-backend/react";

function NewMessageForm(Props) {
  var channelId = Props.channelId;
  var match = React.useState(function () {
        return "";
      });
  var setBody = match[1];
  var body = match[0];
  var channel = React$1.useQuerySingleResult(IhpBackend.query("channels").filterWhere("id", channelId));
  var onSubmit = function ($$event) {
    $$event.preventDefault();
    IhpBackend.createRecord("messages", {
          body: body,
          channelId: channelId
        });
    return Curry._1(setBody, (function (param) {
                  return "";
                }));
  };
  var placeholder = "Send Message to " + (
    (channel == null) ? "" : channel.name
  );
  var onChange = function ($$event) {
    return Curry._1(setBody, (function (param) {
                  return $$event.target.value;
                }));
  };
  return React.createElement("form", {
              className: "form-inline d-flex",
              onSubmit: onSubmit
            }, React.createElement("input", {
                  className: "form-control flex-grow-1",
                  id: "newMessageBody",
                  placeholder: placeholder,
                  value: body,
                  onChange: onChange
                }), React.createElement("button", {
                  className: "btn btn-primary"
                }, "Send"));
}

var make = NewMessageForm;

export {
  make ,
  
}
/* react Not a pure module */
