// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as React from "react";
import * as IhpBackend from "ihp-backend";

function NewMessageFormIfLoggedOut(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setLoading = match[1];
  var login = function (param) {
    Curry._1(setLoading, (function (param) {
            return true;
          }));
    IhpBackend.loginWithRedirect();
    return Curry._1(setLoading, (function (param) {
                  return false;
                }));
  };
  return React.createElement("div", {
              className: "text-muted text-center"
            }, React.createElement("p", undefined, "You need to be logged in to write a message."), React.createElement("button", {
                  className: "btn btn-primary ml-auto",
                  disabled: match[0],
                  onClick: login
                }, "Login to Chat"));
}

var make = NewMessageFormIfLoggedOut;

export {
  make ,
  
}
/* react Not a pure module */
