// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Logout from "./Logout.bs.js";
import * as Belt_Array from "../node_modules/rescript/lib/es6/belt_Array.js";
import * as IhpBackend from "ihp-backend";
import * as SidebarChannel from "./SidebarChannel.bs.js";
import * as React$1 from "ihp-backend/react";

function Sidebar(Props) {
  var channelId = Props.channelId;
  var setChannelId = Props.setChannelId;
  var channels = React$1.useQuery(IhpBackend.query("channels").orderBy("name"));
  var newChannelClick = function (param) {
    var name = (prompt('Name:') || '');
    if (name === "") {
      return ;
    }
    IhpBackend.createRecord("channels", {
          name: name
        });
    
  };
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "mb-3 border-bottom"
                }, "Chat"), React.createElement("ul", {
                  className: "nav nav-pills flex-column"
                }, (channels == null) ? "loading" : Belt_Array.map(channels, (function (channel) {
                          return React.createElement(SidebarChannel.make, {
                                      channel: channel,
                                      isActive: channel.id === channelId,
                                      setChannelId: setChannelId,
                                      key: channel.id
                                    });
                        })), React.createElement("li", {
                      className: "nav-item"
                    }, React.createElement("a", {
                          className: "nav-link",
                          href: "#",
                          onClick: newChannelClick
                        }, "+ New Channel"))), React.createElement("hr", undefined), React.createElement(Logout.make, {}));
}

var make = Sidebar;

export {
  make ,
  
}
/* react Not a pure module */
