// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as React from "react";

function SidebarChannel(Props) {
  var channel = Props.channel;
  var isActive = Props.isActive;
  var setChannelId = Props.setChannelId;
  var classNames = "nav-link" + (
    isActive ? " active" : ""
  );
  var onClick = function (param) {
    return Curry._1(setChannelId, (function (param) {
                  return channel.id;
                }));
  };
  return React.createElement("li", {
              className: "nav-item"
            }, React.createElement("a", {
                  className: classNames,
                  href: "#",
                  onClick: onClick
                }, channel.name));
}

var make = SidebarChannel;

export {
  make ,
  
}
/* react Not a pure module */
